blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/mariuslluca/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Check the development documentation for setup and usage information
  - name: Ask a Question
    url: https://github.com/mariuslluca/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community
